from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .views import count_records_on_date
from .views import *


urlpatterns = [
    path('home', index, name='home'),
    path('', index, name='index'),
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('count-records_on_date/', count_records_on_date, name='count_records_on_date'),
    path('api/subjects-by-grade/<int:grade_id>/', subjects_by_grade, name='subjects_by_grade'),
    path('only_district_data', only_district_data, name = 'only_district_data'),
    path('get-district-list', district_data, name = 'district_data'),
    path('get-district', get_district, name = 'get-district'),
    path('institute-pricing', institute_pricing, name = 'institute_pricing'),
    path('walkin-pricing', walkin_pricing, name = 'walkin_pricing'),
    path('teacher-pricing', teacher_pricing, name = 'teacher_pricing'),
    path('teacher-account', teacher_account, name = 'teacher_account'),
    path('institute-account', institute_account, name = 'institute_account'),
    path('teacher-profile', teacher_profile, name = 'teacher_profile'),
    path('teacher-search-apply', teacher_search_apply, name = 'teacher_search_apply'),
    path('my-jobs', my_jobs, name = 'my_jobs'),
    path('teacher-job-in-review', teacher_job_review, name = 'teacher_job_review'),
    path('teacher-interview-call-recived', teacher_interview_call, name = 'teacher_interview_call'),
    path('teacher-pricing-plan', teacher_pricing_plan, name = 'teacher_pricing_plan'),
    path('add-teacher-profile', add_teacher_profile, name = 'add-teacher-profile'),
    path('add-school-profile', add_school_profile, name = 'add-school-profile'),
    path('school-profile', school_profile, name = 'school_profile'),
    path('school-account', school_account, name = 'school_account'),
    path('post-job', post_job, name = 'post_job'),
    path('edit-job', edit_job, name = 'edit_job'),
    path('walkin-job/', walkin_job, name='walkin_job'),
    path('edit-job-submit', edit_job_submit, name = 'edit_job_submit'),
    path('application-received', application_received, name = 'application-received'),
    path('job-posted', job_posted, name = 'job_posted'),
    path('job-posted-all', job_posted_all, name = 'job_posted_all'),
    path('job-pending', job_pending, name = 'job_pending'),
    path('invited-for-interview', invited_for_interview, name = 'invited_for_interview'),
    path('expired-jobs-reapproval-request', expired_jobs_reapproval_request, name = 'expired_jobs_reapproval_request'),
    path('institute-pricing-plan', institute_pricing_plan, name = 'institute_pricing_plan'),
    path('help-support', help_support, name = 'help_support'),
    path('current-vacancies', current_vacancies, name = 'current_vacancies'),
    path('find-teachers', find_teachers, name = 'find_teachers'),
    path('add-location-db', add_location_db, name = 'add_location_db'),
    path('add-only-location-db', add_only_location_db, name = 'add_only_location_db'),
    path('edit-location-db', edit_location_db, name = 'edit_location_db'),
    path('add-job-alert', add_job_alert, name = 'add_job_alert'),
    path('reject-application', reject_application, name = 'reject-application'),
    path('edit-location-db-job-alert', edit_location_db_job_alert, name = 'edit_location_db_job_alert'),
    path('teacher-application-rejected', teacher_application_rejected, name = 'teacher_application_rejected'),
    path('forgot-password-pin', forgot_password_pin, name = 'forgot-password-pin'),
    path('apply-for-job', apply_for_job, name = 'apply-for-job'),
    path('job-alert', job_alert, name = 'job_alert'),
    path('add-job', add_job, name ='add-job'),
    path('load_subject', load_subject, name = 'load_subject'),
    path('get_teacher_subjects', get_teacher_subjects, name = 'get_teacher_subjects'),
    path('read_csv_file', read_csv_file, name = 'read_csv_file'),
    path('test_auth', test_auth, name = 'test_auth'),
    path('call-for-interview', request_for_interview, name = 'call-for-interview'),
    path('call_for_interview_school', call_for_interview_school, name = 'call_for_interview_school'),
    path('employer-details', employer_details, name = 'employer-details'),
    path('job-details', job_details, name = 'job-details'),
    path('teacher-shortlisted', teacher_shortlisted, name = 'teacher-shortlisted'),
    path('school-shortlisted', school_shortlisted, name = 'school-shortlisted'),
    path('delete-location/', delete_location, name='delete_location'),
    path('delete-all-locations/', delete_all_locations, name='delete_all_locations'),
    path('delete-district/', delete_district, name='delete_district'),



# Admin Dashboard 
    path('admin-dashboard', admin_dashboard, name = 'admin_dashboard'),
    path('current-application', current_application, name = 'current_application'),
    path('approved-application', approved_application, name = 'approved_application'),
    path('recent-login-teacher', recent_login_teacher, name = 'recent_login_teacher'),
    path('recent-login-school', recent_login_school, name = 'recent_login_school'),
    path('verified-teachers', verified_teachers, name = 'verified_teachers'),
    path('unverified-teachers', unverified_teachers, name = 'unverified_teachers'),
    path('verified-institutions', verified_institutions, name = 'verified_institutions'),
    path('unverified-institutions', unverified_institutions, name = 'unverified_institutions'),
    path('admin-job-alert', admin_job_alert, name = 'admin_job_alert'),
    path('teacher-payment/', teacher_payment, name='teacher_payment'),
    path('get-payment-details/', get_payment_details, name='get_payment_details'),
    path('export-payments/', export_payments, name='export_payments'),
    path('school-payment/', school_payment, name='school_payment'),
    path('get-school-payment-details/', get_school_payment_details, name='get_school_payment_details'),
    path('export-school-payments/', export_school_payments, name='export_school_payments'),
    path('admin-my-jobs', admin_my_jobs, name = 'admin_my_jobs'),
    path('active-jobs', active_jobs, name = 'active_jobs'),
    path('admin-expired-jobs', admin_expired_jobs, name = 'admin_expired_jobs'),
    path('pending-approval', pending_approval, name = 'pending_approval'),
    path('admin-post-job', admin_post_job, name = 'admin_post_job'),
    path('admin-walkin-job', admin_walkin_job, name = 'admin_walkin_job'),
    path('admin-settings', admin_settings, name = 'admin_settings'),
    path('application-detail', application_detail, name = 'application_detail'),
    path('expired-teachers-approval', expired_teachers_approval, name = 'expired-teachers-approval'),
    path('interview-calls-school', interview_calls_school, name = 'interview-calls-school'),
    path('interview-calls-school-none', interview_calls_school_none, name = 'interview-calls-school-none'),
    path('new-interview-calls', new_interview_calls, name = 'new-interview-calls'),
    path('approved-interview-calls', approved_interview_calls, name = 'approved-interview-calls'),
    path('call-for-interview-school', call_for_interview_school, name = 'call-for-interview-school'),
     path('admin-add-job', admin_add_job, name = 'admin-add-job'),
    # Razorpay
    path('success_razor_pay_payment/',success_razor_pay_payment, name = 'success_razor_pay_payment'), 
    path('fail_razor_pay_payment/',fail_razor_pay_payment, name = 'fail_razor_pay_payment'),
    path('razorpay-webhook/',razor_pay_webhook, name = 'razor_pay_webhook'),
    path('add-subscription', add_subscription, name='add-subscription'),
    path('add-walkin-subscription', add_walkin_subscription, name = 'add_walkin_subscription'),
    path('walkin-pricing/', walkin_pricing, name='walkin_pricing'),
    path('walkin-job-form/', walkin_job_form, name='walkin_job_form'),
    path('post-walkin-job', post_walkin_job, name='post_walkin_job'),

    #Whatsapp
    path('send-whatsapp', send_whatsapp_school, name='send_whatsapp_school'),
    path('send-whatsapp-teacher-welcome', send_whatsapp_teacher_welcome, name='send-whatsapp-teacher-welcome'),
    path('send-whatsapp-school-welcome', send_whatsapp_school_welcome, name='send-whatsapp-school-welcome'),
    
    
    path('send_pin_teacher', send_pin_teacher, name='send_pin_teacher'),
    path('approve_teacher', approve_teacher, name='approve_teacher'),
    path('disable_teacher', disable_teacher, name='disable_teacher'),
    
    path('approve_application', approve_application, name='approve_application'),

    path('app_details', app_details, name='app_details'),
    path('send_interview_details', send_interview_details, name='send_interview_details'),
    path('reject_application', reject_application, name='reject_application'),
    path('admin_approve', admin_approve, name='admin_approve'),
    path('log_entry', log_entry, name='log_entry'),
    path('change_labels', change_labels, name='change_labels'),
    path('job-application', job_application, name='job-application'),
    path('job-application-candidate', job_application_candidate, name='job-application-candidate'),
    path('set_promotion', set_promotion, name='set_promotion'),
    path('call_for_interview_submit', call_for_interview_submit, name='call_for_interview_submit'),

    path('shortlisted', shortlisted, name='shortlisted'),
    path('old-shortlisted', old_shortlisted, name='old_shortlisted'),
    path('review_shortlisted',review_shortlisted, name='review_shortlisted'),
    path('rejected-applications', rejected_applications, name='rejected-applications'),
    path('rejected-teachers', rejected_teachers, name='rejected-teachers'),
    path('rejected-schools', rejected_schools, name='rejected-schools'),
    path('rejected-jobs', rejected_jobs, name='rejected-jobs'),

    path('custom_whatsapp_form', custom_whatsapp_form, name='custom_whatsapp_form'),
    path('custom_whatsapp_form_job_alert', custom_whatsapp_form_job_alert, name='custom_whatsapp_form_job_alert'),
    path('toggle-welcome-message-controler/',toggle_welcome_message_controler, name= "toggle_welcome_message_controler"),

    path('selected_job_alert_delete', selected_job_alert_delete, name="selected_job_alert_delete"),
    path('change-pin', change_pin, name="change_pin"),
    path("save-lead", save_lead, name="save_lead"),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
